apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auroraos.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auroraos.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "auroraos.name" . }}
    spec:
      containers:
        - name: auroraos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 9701
          livenessProbe:
            httpGet:
              path: /api/status
              port: 9701
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/status
              port: 9701
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
